FBDI Import and Bulk Extract
oracle-livelabs/oic pull request #26
Opened 2023-01-09 06:42 UTC by isubhani006

# 11321 and 11275

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-01-09 17:30 UTC, arabellayao requested changes
Hi! Workshop #11275's link in WMS is oic/oic-gen3/cookbooks/erp-cloud/fdbi-import, and #11321's link is oic/oic-gen3/cookbooks/erp-cloud/bulk-extract, but it seems like you are updating some files outside of those workshops. Could you please make sure the changes only stay in those two workshops, or please add the WMS IDs of all workshops that have been updated? Thanks!

2023-01-10 00:56 UTC, isubhani006 commented
WMS IDs for the changes: 11270, 11275, 11276, 11290, and 11321

2023-01-10 00:57 UTC, isubhani006 commented
I’ve added in the comments section.
Here it is again:
WMSs for the changes: 11270, 11275, 11276, 11290, and 11321

Regards,
Subhani


From: Arabella Yao ***@***.***>
Date: Monday, 9 January 2023 at 23:00
To: oracle-livelabs/oic ***@***.***>
Cc: Subhani Sahib Italapuram ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/oic] FBDI Import and Bulk Extract (PR #26)

@arabellayao requested changes on this pull request.

Hi! Workshop #11275's link in WMS is oic/oic-gen3/cookbooks/erp-cloud/fdbi-import, and #11321's link is oic/oic-gen3/cookbooks/erp-cloud/bulk-extract, but it seems like you are updating some files outside of those workshops. Could you please make sure the changes only stay in those two workshops, or please add the WMS IDs of all workshops that have been updated? Thanks!

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-livelabs/oic/pull/26*pullrequestreview-1240884674__;Iw!!ACWV5N9M2RV99hQ!MfGvcunhu6-j8NZyVX9KOxF9Z7VCiOWZgb1j1s8S-ZHZQRtDv19eXzMYjej03kjfCTcfH-hgmZy4tsC8-9kzn6cADHBZFV4$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/ATMZ32VHP6BGTOTV7YCIFUTWRRDK3ANCNFSM6AAAAAATVCJKR4__;!!ACWV5N9M2RV99hQ!MfGvcunhu6-j8NZyVX9KOxF9Z7VCiOWZgb1j1s8S-ZHZQRtDv19eXzMYjej03kjfCTcfH-hgmZy4tsC8-9kzn6cAkaYjYvw$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-10 14:19 UTC, malcherm approved these changes

2023-01-10 14:19 UTC, merged